# Generated by Django 5.0.4 on 2024-04-18 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pending_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('term_period', models.IntegerField()),
                ('disbursement_date', models.DateField()),
                ('loan_status', models.CharField(choices=[('Pending', 'PENDING'), ('Paid', 'PAID')], max_length=10)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_duedate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finops.loan')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aadhar_id', models.CharField(max_length=12, unique=True)),
                ('credit_score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finops.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finops.userprofile'),
        ),
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_date', models.DateField()),
                ('due_date', models.DateField()),
                ('pay_status', models.CharField(choices=[('Pending', 'PENDING'), ('Paid', 'PAID')], max_length=10)),
                ('amount_to_be_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='Finops.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finops.userprofile')),
            ],
        ),
    ]
