# Generated by Django 5.0.4 on 2024-04-19 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finops', '0002_alter_loan_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='monthly_amount',
            new_name='monthly_payment',
        ),
    ]
